// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------------- //
// audio_i2s_clkout //
// ---------------- //

#define audio_i2s_clkout_wrap_target 0
#define audio_i2s_clkout_wrap 7

#define audio_i2s_clkout_offset_entry_point 7u

static const uint16_t audio_i2s_clkout_program_instructions[] = {
            //     .wrap_target
    0x6001, //  0: out    pins, 1         side 0     
    0x0840, //  1: jmp    x--, 0          side 1     
    0x7001, //  2: out    pins, 1         side 2     
    0xf83e, //  3: set    x, 30           side 3     
    0x7001, //  4: out    pins, 1         side 2     
    0x1844, //  5: jmp    x--, 4          side 3     
    0x6001, //  6: out    pins, 1         side 0     
    0xe83e, //  7: set    x, 30           side 1     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program audio_i2s_clkout_program = {
    .instructions = audio_i2s_clkout_program_instructions,
    .length = 8,
    .origin = -1,
};

static inline pio_sm_config audio_i2s_clkout_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + audio_i2s_clkout_wrap_target, offset + audio_i2s_clkout_wrap);
    sm_config_set_sideset(&c, 2, false, false);
    return c;
}

// ---------------------------------------------------------------------------
// audio_i2s_clkout_program_init — Configure a PIO state machine for 24-bit I2S
//
// Parameters:
//   pio            — PIO block (pio0, pio1, or pio2)
//   sm             — State machine index (0-3)
//   offset         — Instruction memory offset from pio_add_program()
//   data_pin       — GPIO for serial audio data (independently assignable)
//   clock_pin_base — GPIO for BCK; LRCLK is always clock_pin_base + 1
//                    (PIO side-set hardware constraint)
// ---------------------------------------------------------------------------
static inline void audio_i2s_clkout_program_init(PIO pio, uint sm, uint offset,
                                              uint data_pin, uint clock_pin_base) {
    pio_sm_config sm_config = audio_i2s_clkout_program_get_default_config(offset);
    // Serial data: one output pin
    sm_config_set_out_pins(&sm_config, data_pin, 1);
    // Clock signals: BCK on side-set bit 0, LRCLK on side-set bit 1
    sm_config_set_sideset_pins(&sm_config, clock_pin_base);
    // MSB-first, autopull at 32 bits (one channel per FIFO word)
    sm_config_set_out_shift(&sm_config, false, true, 32);
    // Join both FIFOs for TX (doubles TX depth to 8 words)
    sm_config_set_fifo_join(&sm_config, PIO_FIFO_JOIN_TX);
    // Initialize the state machine
    pio_sm_init(pio, sm, offset, &sm_config);
    // Configure pin directions: data pin + BCK + LRCLK as outputs
    uint pin_mask = (1u << data_pin) | (3u << clock_pin_base);
    pio_sm_set_pindirs_with_mask(pio, sm, pin_mask, pin_mask);
    // Drive all pins low initially
    pio_sm_set_pins(pio, sm, 0);
    // Jump to the entry point (starts with Right channel, BCK high)
    pio_sm_exec(pio, sm, pio_encode_jmp(offset + audio_i2s_clkout_offset_entry_point));
}

#endif

