// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------------- //
// audio_i2s_dataout //
// ----------------- //

#define audio_i2s_dataout_wrap_target 0
#define audio_i2s_dataout_wrap 7

#define audio_i2s_dataout_offset_entry_point 7u

static const uint16_t audio_i2s_dataout_program_instructions[] = {
            //     .wrap_target
    0x6001, //  0: out    pins, 1                    
    0x0040, //  1: jmp    x--, 0                     
    0x6001, //  2: out    pins, 1                    
    0xe03e, //  3: set    x, 30                      
    0x6001, //  4: out    pins, 1                    
    0x0044, //  5: jmp    x--, 4                     
    0x6001, //  6: out    pins, 1                    
    0xe03e, //  7: set    x, 30                      
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program audio_i2s_dataout_program = {
    .instructions = audio_i2s_dataout_program_instructions,
    .length = 8,
    .origin = -1,
};

static inline pio_sm_config audio_i2s_dataout_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + audio_i2s_dataout_wrap_target, offset + audio_i2s_dataout_wrap);
    return c;
}

// ---------------------------------------------------------------------------
// audio_i2s_dataout_program_init — Configure a PIO SM for I2S slave (data only)
//
// Unlike the master init, this does NOT configure side-set pins or set
// BCK/LRCLK pin directions. The master SM exclusively owns the clock pins.
//
// Parameters:
//   pio      — PIO block (must be same block as the master SM)
//   sm       — State machine index (0-3)
//   offset   — Instruction memory offset from pio_add_program()
//   data_pin — GPIO for serial audio data (independently assignable)
// ---------------------------------------------------------------------------
static inline void audio_i2s_dataout_program_init(PIO pio, uint sm, uint offset,
                                                    uint data_pin) {
    pio_sm_config sm_config = audio_i2s_dataout_program_get_default_config(offset);
    // Serial data: one output pin (no side-set — slave doesn't drive clocks)
    sm_config_set_out_pins(&sm_config, data_pin, 1);
    // MSB-first, autopull at 32 bits (one channel per FIFO word)
    sm_config_set_out_shift(&sm_config, false, true, 32);
    // Join both FIFOs for TX (doubles TX depth to 8 words)
    sm_config_set_fifo_join(&sm_config, PIO_FIFO_JOIN_TX);
    // Initialize the state machine
    pio_sm_init(pio, sm, offset, &sm_config);
    // Configure ONLY the data pin as output — do NOT touch BCK/LRCLK
    pio_sm_set_consecutive_pindirs(pio, sm, data_pin, 1, true);
    // Drive data pin low initially
    pio_sm_set_pins_with_mask(pio, sm, 0, 1u << data_pin);
    // Jump to entry point (matches master's start position)
    pio_sm_exec(pio, sm, pio_encode_jmp(offset + audio_i2s_dataout_offset_entry_point));
}

#endif

