// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// audio_mck //
// --------- //

#define audio_mck_wrap_target 0
#define audio_mck_wrap 1

static const uint16_t audio_mck_program_instructions[] = {
            //     .wrap_target
    0xb042, //  0: nop                    side 1     
    0xa042, //  1: nop                    side 0     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program audio_mck_program = {
    .instructions = audio_mck_program_instructions,
    .length = 2,
    .origin = -1,
};

static inline pio_sm_config audio_mck_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + audio_mck_wrap_target, offset + audio_mck_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}

// ---------------------------------------------------------------------------
// audio_mck_program_init — Configure a PIO state machine for MCK generation
//
// Parameters:
//   pio    — PIO block (typically pio1)
//   sm     — State machine index (typically 1, since SM0 is PDM)
//   offset — Instruction memory offset from pio_add_program()
//   pin    — GPIO for MCK output
// ---------------------------------------------------------------------------
static inline void audio_mck_program_init(PIO pio, uint sm, uint offset, uint pin) {
    pio_sm_config sm_config = audio_mck_program_get_default_config(offset);
    // MCK on side-set pin
    sm_config_set_sideset_pins(&sm_config, pin);
    // Initialize the state machine
    pio_sm_init(pio, sm, offset, &sm_config);
    // Pin direction: output
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
    // Drive low initially
    pio_sm_set_pins(pio, sm, 0);
}

#endif

